branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"
before_install:
  - cpanm --notest Test::Code::TidyAll 
  - cpanm --notest Test::Perl::Critic
  - cpanm --notest Test::Version
services:
  - mongodb

